- src/Google.Events.Protobuf/Cloud/PubSub/V1/ConverterAttributes.cs
> Fix comment (which was in an unsaved file, unfortunately)

- src/Google.Events.Protobuf/Cloud/PubSub/V1/ConverterAttributes.cs
- src/Google.Events.SystemTextJson.Tests/ConverterAttributeTest.cs
- src/Google.Events.SystemTextJson.Tests/Google.Events.SystemTextJson.Tests.csproj
- src/Google.Events.SystemTextJson.Tests/JsonCloudEventDataConverterTest.cs
- src/Google.Events.SystemTextJson.Tests/ProtoComparisonTest.cs
- src/Google.Events.SystemTextJson/Cloud/Audit/V1/AuditLogData.g.cs
- src/Google.Events.SystemTextJson/Cloud/Firestore/V1/DocumentEventData.cs
- src/Google.Events.SystemTextJson/Cloud/PubSub/V1/MessagePublishedData.cs
- src/Google.Events.SystemTextJson/Cloud/PubSub/V1/MessagePublishedData.g.cs
- src/Google.Events.SystemTextJson/Cloud/Scheduler/V1/SchedulerData.cs
- src/Google.Events.SystemTextJson/Cloud/Storage/V1/StorageObjectData.g.cs
- src/Google.Events.SystemTextJson/Firebase/V1/DocumentEventData.cs
- src/Google.Events.SystemTextJson/Google.Events.SystemTextJson.csproj
- src/Google.Events.SystemTextJson/JsonCloudEventDataConverter.cs
- src/Google.Events.SystemTextJson/JsonConverters.cs
- src/Google.Events.SystemTextJson/Rpc/Code.cs
- src/Google.Events.SystemTextJson/Rpc/Status.cs
- src/Google.Events.SystemTextJson/Type/LatLng.cs
- src/Google.Events.sln
Once this is merged, I'll publish a 1.0.0-alpha01 and start consuming it from the Functions Framework.
> Add System.Text.Json project for CloudEvents

- src/Google.Events.Protobuf/Google.Events.Protobuf.csproj
- src/Google.Events.SystemTextJson/Google.Events.SystemTextJson.csproj
- src/Google.Events/Google.Events.csproj
> Improve package descriptions

- BUILDING.md
- README.md
Fixes #6 as far as we need to for now.
> Add more documentation, now that we have published packages

- src/Google.Events.SystemTextJson.Tests/ProtoComparisonTest.cs
- src/Google.Events.SystemTextJson/Cloud/Storage/V1/StorageObjectData.g.cs
We might eventually want to exclude JsonIgnore ones, but we can do
that if we actually need to.
> Check that all JSON properties are in protos

- src/ProductionProperties.xml
Changes since 1.0.0-alpha02:
- Improved package descriptions
- Changes to event data classes reflecting changes in https://github.com/googleapis/google-cloudevents
- Each event data class now contains CloudEvent type constants
> Release 1.0.0-alpha03

- .github/workflows/build.yml
- .travis.yml
> Migrate from Travis to GitHub Actions.

- src/Google.Events.ValidateSchema/Google.Events.ValidateSchema.csproj
Fortunately I caught this instead of accidentally publishing it :)
> Make the ValidateSchema package non-packable

- src/ProductionProperties.xml
This will publish all Google.Events packages.
Changes in this release:
- Update tool and package dependencies
- Regenerate all protos
> Release Google.Events version 1.0.0-alpha06

- RELEASING.md
> Add release documentation

- src/Google.Events.Protobuf/Cloud/Firestore/V1/Data.g.cs
- src/Google.Events.Protobuf/Firebase/RemoteConfig/V1/Data.g.cs
(One comment change; one metadata change.)
> Regenerate all events

- src/ProductionProperties.xml
Changes since 1.0.0-beta05:
- Updated to CloudNative.CloudEvents version 2.0.0
- Regenerate all event (only affects a comment and some metadata)
> Release Google.Events.Protobuf version 1.0.0

- src/Google.Events.ValidateSchema/Program.cs
Addresses #66 as far as we can.
> Make it clearer which test has failed

- .github/renovate.json
This does not update our production project, where we control all
the dependencies manually, but will update tests, tooling etc.
> Add Renovate dependency automation

- .github/renovate.json
> chore: Disable the Renovate dashboard

- .github/workflows/build.yml
- generate-code.sh
- global.json
- src/Google.Events.Protobuf.Tests/Google.Events.Protobuf.Tests.csproj
- src/Google.Events.Protobuf/Cloud/Audit/V1/Data.g.cs
- src/Google.Events.Protobuf/Google.Events.Protobuf.csproj
- src/Google.Events.ValidateSchema/Google.Events.ValidateSchema.csproj
- tools/Google.Events.Tools.CodeGenerator/Google.Events.Tools.CodeGenerator.csproj
- validate-schema.sh
This is in preparation for a 1.1.0 release.
> Regenerate events and update dependencies

- src/ProductionProperties.xml
Changes since 1.0.0:
- Dependency updates
- Added FirebaseAlerts events
- Regenerated all existing events
> Release Google.Events.Protobuf version 1.1.0

- src/Google.Events.Protobuf/Cloud/Audit/V1/Data.g.cs
- src/Google.Events.Protobuf/Google.Events.Protobuf.csproj
(I won't trigger a release from this; we'll wait until there's something more significant.)
> Update dependencies and regenerate from protos

- generate-code.sh
- src/Google.Events.Protobuf/Cloud/ApiGateway/V1/Data.g.cs
- src/Google.Events.Protobuf/Cloud/ApigeeRegistry/V1/Data.g.cs
- src/Google.Events.Protobuf/Cloud/Audit/V1/Data.g.cs
- src/Google.Events.Protobuf/Cloud/BeyondCorp/AppConnections/V1/Data.g.cs
- src/Google.Events.Protobuf/Cloud/BeyondCorp/AppConnectors/V1/Data.g.cs
- src/Google.Events.Protobuf/Cloud/BeyondCorp/AppGateways/V1/Data.g.cs
- src/Google.Events.Protobuf/Cloud/CertificateManager/V1/Data.g.cs
- src/Google.Events.Protobuf/Cloud/CloudBuild/V1/Data.g.cs
- src/Google.Events.Protobuf/Cloud/CloudDms/V1/Data.g.cs
- src/Google.Events.Protobuf/Cloud/DataFusion/V1/Data.g.cs
- src/Google.Events.Protobuf/Cloud/Datastream/V1/Data.g.cs
- src/Google.Events.Protobuf/Cloud/Eventarc/V1/Data.g.cs
- src/Google.Events.Protobuf/Cloud/Firestore/V1/Data.g.cs
- src/Google.Events.Protobuf/Cloud/Functions/V2/Data.g.cs
- src/Google.Events.Protobuf/Cloud/Iot/V1/Data.g.cs
- src/Google.Events.Protobuf/Cloud/Memcache/V1/Data.g.cs
- src/Google.Events.Protobuf/Cloud/PubSub/V1/Data.g.cs
- src/Google.Events.Protobuf/Cloud/Storage/V1/Data.g.cs
- src/Google.Events.Protobuf/Cloud/Workflows/V1/Data.g.cs
- src/Google.Events.Protobuf/Firebase/Analytics/V1/Data.g.cs
- src/Google.Events.Protobuf/Firebase/TestLab/V1/Data.g.cs
- src/Google.Events.Protobuf/Google.Events.Protobuf.csproj
- src/Google.Events.ValidateSchema/Google.Events.ValidateSchema.csproj
- tools/Google.Events.Tools.CodeGenerator/Google.Events.Tools.CodeGenerator.csproj
- validate-schema.sh
(I'd recommend reviewing the commits separately; the first is manual, but the second is purely generated.)
> chore: Update to Google.Protobuf 3.22

- .kokoro/pip-requirements.txt
- .kokoro/requirements.txt
These are now the same as for google-cloud-dotnet, for simplicity of updating.
> chore: Update pip requirements files

- src/Google.Events.Protobuf/StructExtensions.cs
> docs: Minor tweak in code documentation.

- .github/workflows/build.yml
- global.json
- src/Google.Events.Protobuf.Tests/Google.Events.Protobuf.Tests.csproj
- src/Google.Events.ValidateSchema/Google.Events.ValidateSchema.csproj
- tools/Google.Events.Tools.CodeGenerator/Google.Events.Tools.CodeGenerator.csproj
> deps: Build and test with .NET 8
